name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: uname -a

    - env:
        MKN_LIB_LINK_LIB: 1
        KUL_GIT_CO: --depth 1
      run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++17 -fPIC"
